// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Zw_ygNvdmapGVtp6CLuIj5zT4YOJPAA',
    appId: '1:781529753465:android:094ae55310ab2be88ff1a8',
    messagingSenderId: '781529753465',
    projectId: 'chat-app-85ffa',
    storageBucket: 'chat-app-85ffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHKxu6-CdsmLQN64O8gl6CdZDVy5E1zEc',
    appId: '1:781529753465:ios:1e5fb7cfabfdc3998ff1a8',
    messagingSenderId: '781529753465',
    projectId: 'chat-app-85ffa',
    storageBucket: 'chat-app-85ffa.appspot.com',
    androidClientId: '781529753465-nt7k4m1s9g6m9o11t137ojpetmavrqpd.apps.googleusercontent.com',
    iosClientId: '781529753465-rpsmahcsaqhc14f0a2l5o59rjk5ld641.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}